### PR TITLE
Allow registration under a different namespace than the modid

### PR DESCRIPTION
**Pull request by Rover656**
Allows you to register objects in a specific domain from another modid.

Was done pretty quickly, lemme know if anything needs changed 😄

### CODE REVIEW

**Comment by tterrag1098** [comment]
This needs better javadocs, as well as a better explanation of the purpose. What is the distinction between "modid" and "domain" here? To me, a domain is a concept of resources/data, not registry objects. Registry objects always belong to a mod, not any random domain name.

I understand what you're trying to accomplish, but only because I have the context of the reason behind this PR. Someone reading this without that context would not be able to guess the distinction between the two.

**Comment by Rover656** [comment]
Understood - I'll get onto this once I'm next available. Thanks for the review.

**Comment by Rover656** [comment]
I have updated the javadocs and renamed domain to namespace to generalise the term. Should be okay for a second review :)

**Comment by Rover656** [comment]
Yeah so this just isn't needed, I'm gonna close.

**Pull request closed without merging**
